#!/usr/bin/env bash
# Configure a new Nginx server so that /redirect_me is redirecting to another page
#+ The redirection must be a “301 Moved Permanently”

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 http://cuberule.com/;
    }
}"
sudo service nginx start
newlines="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "26i $newlines" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
